brands = [
    {
        "Id": 1,
        "Name": "Apple Inc.",
        "Logo": "https://upload.wikimedia.org/wikipedia/commons/f/fa/Apple_logo_black.svg",
        "Description": "Apple Inc. is an American multinational technology company that designs, develops and sells consumer electronics, software, and online services. It is considered one of the big four of technology along with Amazon, Google, and Facebook. Apple is the world’s largest information technology company by revenue and world’s third-largest mobile phone manufacturer after Samsung and Huawei. Apple has high level of brand loyalty and is ranked world’s most valuable brand. However, Apple receives significant criticism regarding the labor practices of its contractors, its environmental practices and unethical business practices, including anti-competitive behavior, as well as the origins of source materials.",
        "Founded": 1976,
        "Industry": ["Computer Hardware", "Computer Software", "Consumer Electronics"],
        "Headquarters": "California",
        "Revenue": 265.596,
        "NetIncome": 59.531,
        "Ranking": 1,
        "Percent": 16,
        "Growth": 214480,
        "URL": "www.apple.com"
    },
    {
        "Id": 2,
        'Name': 'Google LLC',
        'Logo': 'https://upload.wikimedia.org/wikipedia/commons/2/2f/Google_2015_logo.svg',
        'Description': "Google LLC is an American multinational technology company that specializes in Internet-related services and products, which include online advertising technologies, search engine, cloud computing, software, and hardware. It is considered one of the Big Four technology companies, alongside Amazon, Apple and Facebook. The company's rapid growth since incorporation has triggered a chain of products, acquisitions, and partnerships beyond Google's core search engine (Google Search). Google.com is the most visited website in the world. Several other Google services also figure in the top 100 most visited websites, including YouTube and Blogger. Google is the most valuable brand in the world as of 2017, but has received significant criticism involving issues such as privacy concerns, tax avoidance, antitrust, censorship, and search neutrality. Google's mission statement is 'to organize the world's information and make it universally accessible and useful'.",
        'Founded': 1998,
        'Industry': ['Internet', 'Software', 'Computer hardware'],
        'Headquarters': 'California',
        'Revenue': 109.65,
        'NetIncome': 30.74,
        "Ranking": 2,
        "Percent": 10,
        "Growth": 155506,
        'URL': 'www.google.com'
    },
    {
        "Id": 3,
        'Name': 'Amazon.com, Inc.',
        'Logo': "https://upload.wikimedia.org/wikipedia/commons/7/70/Amazon_logo_plain.svg",
        'Description': "Amazon is an American multinational technology company based in Seattle, Washington that focuses in e-commerce, cloud computing, and artificial intelligence. Amazon.com was founded by Jeff Bezos on July 5, 1994, and started as an online bookstore but later diversified to sell video downloads/streaming, MP3 downloads/streaming, audiobook downloads/streaming, software, video games, electronics, apparel, furniture, food, toys, and jewelry. Amazon is the largest e-commerce marketplace and cloud computing platform in the world as measured by revenue and market capitalization. Amazon is the largest Internet company by revenue in the world and the second largest employer in the United States.",
        'Founded': 1994,
        'Industry': ['Cloud computing', 'Consumer electronics', 'Digital distribution'],
        'Headquarters': 'Washington',
        'Revenue': 232.887,
        'NetIncome': 10.073,
        "Ranking": 3,
        "Percent": 56,
        "Growth": 100764,
        'URL': 'www.amazon.com'
    },
    {
        "Id": 4,
        'Name': 'Microsoft Corporation',
        'Logo': "https://upload.wikimedia.org/wikipedia/commons/9/96/Microsoft_logo_%282012%29.svg",
        'Description': "Microsoft Corporation  is an American multinational technology company with headquarters in Redmond, Washington. It develops, manufactures, licenses, supports and sells computer software, consumer electronics, personal computers, and related services. Its best known software products are the Microsoft Windows line of operating systems, the Microsoft Office suite, and the Internet Explorer and Edge web browsers. Since Satya Nadella took over as CEO in 2014, the company has scaled back on hardware and has instead focused on cloud computing, a move that helped the company's shares reach its highest value since December 1999. In 2018, Microsoft surpassed Apple as the most valuable publicly traded company in the world after being dethroned by the tech giant in 2010.",
        'Founded': 1975,
        'Industry': ['Computer software', 'Computer hardware', 'Consumer electronics'],
        'Headquarters': 'Washington',
        'Revenue': 110.36,
        'NetIncome': 16.57,
        "Ranking": 4,
        "Percent": 16,
        "Growth": 92715,
        'URL': 'www.microsoft.com'
    },
    {
        "Id": 5,
        'Name': 'The Coca-Cola Company',
        'Logo': "https://upload.wikimedia.org/wikipedia/commons/5/5e/The_Coca-Cola_Company_logo.svg",
        'Description': "The Coca-Cola Company is an American corporation, and manufacturer, retailer, and marketer of nonalcoholic beverage concentrates and syrups. The company is best known for its flagship product Coca-Cola, invented in 1886 by pharmacist John Stith Pemberton in Atlanta, Georgia. The Coca-Cola formula and brand were fully bought with US$2,300 in 1889 by Asa Griggs Candler, who incorporated The Coca-Cola Company in Atlanta in 1892. The company—headquartered in Atlanta, Georgia, but incorporated in Wilmington, Delaware—has operated a franchised distribution system since 1889: the Company only produces syrup concentrate, which is then sold to various bottlers throughout the world who hold exclusive territories.",
        'Founded': 1886,
        'Industry': ['Beverages', 'Food', 'Soft Drinks'],
        'Headquarters': 'Georgia',
        'Revenue': 35.41,
        'NetIncome': 1.248,
        "Ranking": 5,
        "Percent": -5,
        "Growth": 66341,
        'URL': 'www.coca-cola.com'
    },
    {
        "Id": 6,
        'Name': 'Samsung',
        'Logo': "https://upload.wikimedia.org/wikipedia/commons/b/b4/Samsung_wordmark.svg",
        'Description': "Samsung is a South Korean multinational conglomerate headquartered in Samsung Town, Seoul. It comprises numerous affiliated businesses, most of them united under the Samsung brand, and is the largest South Korean chaebol (business conglomerate). Samsung was founded by Lee Byung-chul in 1938 as a trading company. Over the next three decades, the group diversified into areas including food processing, textiles, insurance, securities, and retail. Samsung has a powerful influence on South Korea's economic development, politics, media and culture and has been a major driving force behind the 'Miracle on the Han River'. Its affiliate companies produce around a fifth of South Korea's total exports.[16] Samsung's revenue was equal to 17% of South Korea's $1,082 billion GDP.",
        'Founded': 1938,
        'Industry': ['Conglomerate', 'Electronics', 'Home Appliances'],
        'Headquarters': 'South Korea',
        'Revenue': 210.9,
        'NetIncome': 37.1,
        "Ranking": 6,
        "Percent": 6,
        "Growth": 59890,
        'URL': 'www.samsung.com'
    },
    {
        "Id": 7,
        'Name': 'Toyota Motor Corporation',
        'Logo': "https://upload.wikimedia.org/wikipedia/commons/9/9d/Toyota_carlogo.svg",
        'Description': "Toyota Motor Corporation is a Japanese multinational automotive manufacturer headquartered in Toyota City, Aichi, Japan. In 2017, Toyota's corporate structure consisted of 364,445 employees worldwide and, as of September 2018, was the sixth-largest company in the world by revenue. As of 2017, Toyota is the world's second-largest automotive manufacturer. Toyota was the world's first automobile manufacturer to produce more than 10 million vehicles per year which it has done since 2012, when it also reported the production of its 200-millionth vehicle. The company was founded by Kiichiro Toyoda in 1937, as a spinoff from his father's company Toyota Industries to create automobiles.",
        'Founded': 1937,
        'Industry': ['Automotive', 'Automobiles', 'Engines'],
        'Headquarters': 'Japan',
        'Revenue': 265,
        'NetIncome': 23,
        "Ranking": 7,
        "Percent": 6,
        "Growth": 53404,
        'URL': 'www.toyota-global.com'
    },
    {
        "Id": 8,
        'Name': 'Mercedes-Benz',
        'Logo': "https://upload.wikimedia.org/wikipedia/commons/9/9e/Mercedes-Benz_Logo_2010.svg",
        'Description': "Mercedes-Benz is a German global automobile marque and a division of Daimler AG. The brand is known for luxury vehicles, buses, coaches, and trucks. The headquarters is in Stuttgart, Baden-Württemberg. The name first appeared in 1926 under Daimler-Benz. In 2018, Mercedes-Benz was the biggest selling premium vehicle brand in the world, having sold 2.31 million passenger cars. Mercedes-Benz traces its origins to Daimler-Motoren-Gesellschaft's 1901 Mercedes and Karl Benz's 1886 Benz Patent-Motorwagen, which is widely regarded as the first gasoline-powered automobile. The slogan for the brand is 'the best or nothing'.",
        'Founded': 1926,
        'Industry': ['Automotive, Trucks, Buses'],
        'Headquarters': 'Germany',
        'Revenue': 34.8,
        'NetIncome': 0,
        "Ranking": 8,
        "Percent": 2,
        "Growth": 48601,
        'URL': 'www.mercedes-benz.com'
    },
    {
        "Id": 9,
        'Name': 'Facebook, Inc.',
        'Logo': "https://upload.wikimedia.org/wikipedia/commons/8/87/Facebook_Logo_%282015%29_light.svg",
        'Description': "Facebook, Inc. is an American online social media and social networking service company. It is based in Menlo Park, California. It was founded by Mark Zuckerberg, along with fellow Harvard College students and roommates Eduardo Saverin, Andrew McCollum, Dustin Moskovitz and Chris Hughes. It is considered one of the Big Four technology companies along with Amazon, Apple, and Google. Facebook had more than 2.2 billion monthly active users as of January 2018. It receives prominent media coverage, including many controversies such as user privacy and psychological effects. The company has faced intense pressure over censorship and over content that some users find objectionable. Facebook offers other products and services. It acquired Instagram, WhatsApp and Oculus Rift and independently developed Facebook Messenger.",
        'Founded': 2004,
        'Industry': ["Social Networking", "Internet", "Social Media"],
        'Headquarters': 'California',
        'Revenue': 55.838,
        'NetIncome': 22.111,
        "Ranking": 9,
        "Percent": -6,
        "Growth": 45168,
        'URL': 'www.facebook.com'
    },
    {
        "Id": 10,
        'Name': "McDonald's Corporation",
        'Logo': "https://upload.wikimedia.org/wikipedia/commons/3/36/McDonald%27s_Golden_Arches.svg",
        'Description': "McDonald's is an American fast food company, founded in 1940 as a restaurant operated by Richard and Maurice McDonald, in San Bernardino, California, United States. They rechristened their business as a hamburger stand, and later turned the company into a franchise, with the Golden Arches logo being introduced in 1953 at a location in Phoenix, Arizona. McDonald's is the world's largest restaurant chain by revenue, serving over 69 million customers daily in over 100 countries across 37,855 outlets as of 2018. According to a BBC report published in 2012, McDonald's is the world's second-largest private employer (behind Walmart) with 1.9 million employees, 1.5 million of whom work for franchises.",
        'Founded': 1940,
        'Industry': ["Restaurants", "Fast Food", "Global Chain"],
        'Headquarters': 'Illinois',
        'Revenue': 21.025,
        'NetIncome': 5.924,
        "Ranking": 10,
        "Percent": 5,
        "Growth": 43417,
        'URL': 'www.corporate.mcdonalds.com'
    },
    {
        "Id": 11,
        'Name': 'Intel Corporation',
        'Logo': "https://upload.wikimedia.org/wikipedia/commons/c/c9/Intel-logo.svg",
        'Description': "Intel Corporation is an American multinational corporation and technology company headquartered in Santa Clara, California, in the Silicon Valley. It is the world's second largest and second highest valued semiconductor chip manufacturer based on revenue after being overtaken by Samsung, and is the inventor of the x86 series of microprocessors, the processors found in most personal computers (PCs). Intel ranked No. 46 in the 2018 Fortune 500 list of the largest United States corporations by total revenue. Intel supplies processors for computer system manufacturers such as Apple, Lenovo, HP, and Dell. Intel also manufactures motherboard chipsets, network interface controllers and integrated circuits, flash memory, graphics chips, embedded processors and other devices related to communications and computing.",
        'Founded': 1968,
        'Industry': ['Semiconductors', 'Microprocessors', 'Systems-on-Chips'],
        'Headquarters': 'California',
        'Revenue': 70.7,
        'NetIncome': 21.1,
        "Ranking": 11,
        "Percent": 10,
        "Growth": 43293,
        'URL': 'www.intel.com'
    },
    {
        "Id": 12,
        'Name': 'International Business Machines Corporation (IBM)',
        'Logo': "https://upload.wikimedia.org/wikipedia/commons/5/51/IBM_logo.svg",
        'Description': "IBM is an American multinational information technology company headquartered in Armonk, New York, with operations in over 170 countries. The company began in 1911, founded in Endicott, New York, as the Computing-Tabulating-Recording Company (CTR) and was renamed 'International Business Machines' in 1924. IBM produces and sells computer hardware, middleware and software, and provides hosting and consulting services in areas ranging from mainframe computers to nanotechnology. IBM is also a major resea Nicknamed Big Blue, IBM is one of 30 companies included in the Dow Jones Industrial Average and one of the world's largest employers, with (as of 2017) over 380,000 employees, known as 'IBMers'. At least 70% of IBMers are based outside the United States, and the country with the largest number of IBMers is India.rch organization, holding the record for most U.S. patents generated by a business (as of 2019) for 26 consecutive years. Nicknamed Big Blue, IBM is one of 30 companies included in the Dow Jones Industrial Average and one of the world's largest employers, with (as of 2017) over 380,000 employees, known as 'IBMers'. At least 70% of IBMers are based outside the United States, and the country with the largest number of IBMers is India." ,
        'Founded': 1911,
        'Industry': ['Cloud Computing', 'Cognitive Computing', 'Computers'],
        'Headquarters': 'New York',
        'Revenue': 79.591,
        'NetIncome': 8.728,
        "Ranking": 12,
        "Percent": -8,
        "Growth": 42972,
        'URL': 'www.ibm.com'
    },
    {
        "Id": 13,
        'Name': 'Bayerische Motoren Werke AG (BMW)',
        'Logo': "https://upload.wikimedia.org/wikipedia/commons/4/44/BMW.svg",
        'Description': "BMW is a German multinational company which currently produces automobiles and motorcycles, and also produced aircraft engines until 1945. The company was founded in 1916 and is headquartered in Munich, Bavaria. BMW produces motor vehicles in Germany, Brazil, China, India, South Africa, the United Kingdom, and the United States. In 2015, BMW was the world's twelfth largest producer of motor vehicles, with 2,279,503 vehicles produced. The company has significant motorsport history, especially in touring cars, Formula 1, sports cars and the Isle of Man TT.",
        'Founded': 1916,
        'Industry': ['Automotive', 'Cars', 'Motorcycles'],
        'Headquarters': 'Germany',
        'Revenue': 111.64,
        'NetIncome': 9.852,
        "Ranking": 13,
        "Percent": -1,
        "Growth": 41006,
        'URL': 'www.bmw.com'
    },
    {
        "Id": 14,
        'Name': 'The Walt Disney Company',
        'Logo': "https://upload.wikimedia.org/wikipedia/commons/6/65/TWDC_Logo.svg",
        'Description': "The Walt Disney Company is an American diversified multinational mass media and entertainment conglomerate headquartered at the Walt Disney Studios in Burbank, California. It is the world's largest media conglomerate in terms of revenue, ahead of NBCUniversal and WarnerMedia, which are owned by telecommunications giants Comcast and AT&T respectively. The company established itself as a leader in the American animation industry before diversifying into live-action film production, television, and theme parks. Since the 1980s, Disney has created and acquired corporate divisions in order to market more mature content than is typically associated with its flagship family-oriented brands. The company is known for its film studios which include Walt Disney Studios, Marvel Studios, Lucasfilm, 20th Century Fox, Pixar, and Walt Disney Animation Studios. Disney also owns and operates the ABC broadcast network; cable television networks such as Disney Channel, ESPN, Freeform, FX, National Geographic network, and A&E Networks; publishing, merchandising, music, and theater divisions; and Walt Disney Parks and Resorts, a group of 14 theme parks around the world.",
        'Founded': 1923,
        'Industry': ['Mass Media', 'Entertainment', 'Theme Parks'],
        'Headquarters': 'California',
        'Revenue': 59.434,
        'NetIncome': 12.598,
        "Ranking": 14,
        "Percent": -2,
        "Growth": 39874,
        'URL': 'www.thewaltdisneycompany.com'
    },
    {
        "Id": 15,
        'Name': 'Cisco Systems, Inc.',
        'Logo': "https://upload.wikimedia.org/wikipedia/commons/0/08/Cisco_logo_blue_2016.svg",
        'Description': "Cisco Systems, Inc. is an American multinational technology conglomerate headquartered in San Jose, California, in the center of Silicon Valley. Cisco develops, manufactures and sells networking hardware, telecommunications equipment and other high-technology services and products. Through its numerous acquired subsidiaries, such as OpenDNS, WebEx, Jabber and Jasper, Cisco specializes into specific tech markets, such as Internet of Things (IoT), domain security and energy management. Cisco Systems was founded in December 1984 by Leonard Bosack and Sandy Lerner, two Stanford University computer scientists. They pioneered the concept of a local area network (LAN) being used to connect geographically disparate computers over a multiprotocol router system. By the time the company went public in 1990, Cisco had a market capitalization of $224 million. By the end of the dot-com bubble in the year 2000, Cisco had a more than $500 billion market capitalization.",
        'Founded': 1984,
        'Industry': ['Networking Hardware', 'Networking Software', 'LAN'],
        'Headquarters': 'California',
        'Revenue': 49.33,
        'NetIncome': 0.11,
        "Ranking": 15,
        "Percent": 8,
        "Growth": 34575,
        'URL': 'wwww.cisco.com'
    },
    {
        "Id": 16,
        'Name': 'General Electric Company (GE)',
        'Logo': "https://upload.wikimedia.org/wikipedia/commons/f/ff/General_Electric_logo.svg",
        'Description': "General Electric Company (GE) is an American multinational conglomerate incorporated in New York and headquartered in Boston. As of 2018, the company operates through the following segments: aviation, healthcare, power, renewable energy, digital industry, additive manufacturing, venture capital and finance, lighting, and oil and gas. In 2018, GE ranked among the Fortune 500 as the 18th-largest firm in the U.S. by gross revenue. In 2011, GE ranked among the Fortune 20 as the 14th-most profitable company but has since very severely underperformed the market (by about 75%) as its profitability collapsed",
        'Founded': 1892,
        'Industry': ['Conglomerate', 'Aviation', 'Energy'],
        'Headquarters': 'Massachusetts',
        'Revenue': 121.6,
        'NetIncome': -22.8,
        "Ranking": 16,
        "Percent": -26,
        "Growth": 32757,
        'URL': 'www.GE.com'
    },
    {
        "Id": 17,
        'Name': 'Nike, Inc.',
        'Logo': "https://upload.wikimedia.org/wikipedia/commons/a/a6/Logo_NIKE.svg",
        'Description': "Nike, Inc. is an American multinational corporation that is engaged in the design, development, manufacturing, and worldwide marketing and sales of footwear, apparel, equipment, accessories, and services. The company is headquartered near Beaverton, Oregon, in the Portland metropolitan area. It is the world's largest supplier of athletic shoes and apparel and a major manufacturer of sports equipment. As of 2017, the Nike brand is valued at $29.6 billion.[6] Nike ranked No. 89 in the 2018 Fortune 500 list of the largest United States corporations by total revenue. Nike markets its products under its own brand, as well as Nike Golf, Nike Pro, Nike+, Air Jordan, Nike Blazers, Air Force 1, Nike Dunk, Air Max, Foamposite, Nike Skateboarding, Nike CR7, and subsidiaries including Brand Jordan, Hurley International and Converse. Nike sponsors many high-profile athletes and sports teams around the world, with the highly recognized trademarks of 'Just Do It' and the Swoosh logo.",
        'Founded': 1964,
        'Industry': ['Apparel', 'Accessories', 'Sports Equipment'],
        'Headquarters': 'Oregon',
        'Revenue': 36.39,
        'NetIncome': 1.93,
        "Ranking": 17,
        "Percent": 11,
        "Growth": 30120,
        'URL': 'www.nike.com'
    },
    {
        "Id": 18,
        'Name': 'Louis Vuitton (LV)',
        'Logo': "https://upload.wikimedia.org/wikipedia/commons/7/76/Louis_Vuitton_logo_and_wordmark.svg",
        'Description': "Louis Vuitton is a French fashion house and luxury retail company founded in 1854 by Louis Vuitton. The label's LV monogram appears on most of its products, ranging from luxury trunks and leather goods to ready-to-wear, shoes, watches, jewelry, accessories, sunglasses and books. Louis Vuitton is one of the world's leading international fashion houses; it sells its products through standalone boutiques, lease departments in high-end department stores, and through the e-commerce section of its website. The company operates in 50 countries with more than 460 stores worldwide.",
        'Founded': 1854,
        'Industry': ['Fashion', 'Accessories', 'Luxury Goods'],
        'Headquarters': 'France',
        'Revenue': 9.9,
        'NetIncome': 6.35,
        "Ranking": 18,
        "Percent": 23,
        "Growth": 28152,
        'URL': 'www.louisvuitton.com'
    },
    {
        "Id": 19,
        'Name': 'Oracle Corporation',
        'Logo': "https://upload.wikimedia.org/wikipedia/commons/c/c3/Oracle_Logo.svg",
        'Description': "Oracle Corporation is an American multinational computer technology corporation headquartered in Redwood Shores, California. The company specializes primarily in developing and marketing database software and technology, cloud engineered systems, and enterprise software products — particularly its own brands of database management systems. In 2018, Oracle was the third-largest software maker by revenue, after Microsoft and Alphabet. The company also develops and builds tools for database development and systems of middle-tier software, enterprise resource planning (ERP) software, customer relationship management (CRM) software, and supply chain management (SCM) software.",
        'Founded': 1977,
        'Industry': ['Enterprise Software', 'Cloud Computing'],
        'Headquarters': 'California',
        'Revenue': 39.83,
        'NetIncome': 3.82,
        "Ranking": 19,
        "Percent": -5,
        "Growth": 26133,
        'URL': 'www.oracle.com'
    },
    {
        "Id": 20,
        'Name': 'Honda Motor Company, Ltd.',
        'Logo': "https://upload.wikimedia.org/wikipedia/commons/0/09/Honda-logo.svg",
        'Description': "Honda is a Japanese public multinational conglomerate corporation primarily known as a manufacturer of automobiles, aircraft, motorcycles, and power equipment. Honda has been the world's largest motorcycle manufacturer since 1959, as well as the world's largest manufacturer of internal combustion engines measured by volume, producing more than 14 million internal combustion engines each year. n 2013, Honda invested about 5.7% (US$6.8 billion) of its revenues in research and development. Also in 2013, Honda became the first Japanese automaker to be a net exporter from the United States, exporting 108,705 Honda and Acura models, while importing only 88,357.",
        'Founded': 1948,
        'Industry': ['Conglomerate', 'Automotive', 'Motors'],
        'Headquarters': 'Japan',
        'Revenue': 132.7,
        'NetIncome': 3.131,
        "Ranking": 20,
        "Percent": 4,
        "Growth": 23682,
        'URL': 'global.honda'
    },
    {
        "Id": 21,
        'Name': 'SAP SE',
        'Logo': "https://upload.wikimedia.org/wikipedia/commons/5/59/SAP_2011_logo.svg",
        'Description': "SAP SE is a German-based European multinational software corporation that makes enterprise software to manage business operations and customer relations. SAP is headquartered in Walldorf, Baden-Württemberg, Germany with regional offices in 180 countries. The company has over 425,000 customers in over 180 countries and is a component of the Euro Stoxx 50 stock market index.",
        'Founded': 1972,
        'Industry': ['Enterprise Software'],
        'Headquarters': 'Germany',
        'Revenue': 27.962,
        'NetIncome': 4.618,
        "Ranking": 21,
        "Percent": 1,
        "Growth": 22885,
        'URL': 'www.sap.com'
    },
    {
        "Id": 22,
        'Name': 'Pepsi',
        'Logo': "https://upload.wikimedia.org/wikipedia/commons/c/c6/Pepsi_logo_new.svg",
        'Description': "Pepsi is a carbonated soft drink manufactured by PepsiCo. Originally created and developed in 1893 by Caleb Bradham and introduced as Brad's Drink, it was renamed as Pepsi-Cola on August 28, 1898, and then as Pepsi in 1961.",
        'Founded': 1893,
        'Industry': ['Beverages'],
        'Headquarters': 'New York',
        'Revenue': 63.53,
        'NetIncome': 4.908,
        "Ranking": 22,
        "Percent": 2,
        "Growth": 20798,
        'URL': 'www.pepsi.com'
    },
    {
        "Id": 23,
        'Name': 'Chanel S.A.',
        'Logo': "https://upload.wikimedia.org/wikipedia/en/9/92/Chanel_logo_interlocking_cs.svg",
        'Description': "Chanel S.A. is a French privately held company owned by Alain Wertheimer and Gérard Wertheimer, grandsons of Pierre Wertheimer, who was an early business partner of the couturière Coco Chanel. Chanel S.A. is a high fashion house that specializes in haute couture and ready-to-wear clothes, luxury goods, and fashion accessories. In her youth, Gabrielle Chanel gained the nickname Coco from her time as a chanteuse. As a fashion designer, Coco Chanel catered to women's taste for elegance in dress, with blouses and suits, trousers and dresses, and jewellery (gemstone and bijouterie) of simple design, that replaced the opulent, over-designed, and constrictive clothes and accessories of 19th-century fashion.",
        'Founded': 1909,
        'Industry': ['Fashion', 'Accessories', 'Perfume'],
        'Headquarters': 'England',
        'Revenue': 9.6,
        'NetIncome': 1.47,
        "Ranking": 23,
        "Percent": 0,
        "Growth": 20005,
        'URL': 'www.chanel.com'
    },
    {
        "Id": 24,
        'Name': 'American Express Company',
        'Logo': "https://upload.wikimedia.org/wikipedia/commons/f/fa/American_Express_logo_%282018%29.svg",
        'Description': "The American Express Company, also known as Amex, is an American multinational financial services corporation headquartered in Three World Financial Center in New York City. The company was founded in 1850 and is one of the 30 components of the Dow Jones Industrial Average. The company is best known for its charge card, credit card, and traveler's cheque businesses.In 2018, Fortune ranked American Express as the 14th most admired company worldwide, and the 23rd best company to work for. The company's logo, adopted in 1958, is a gladiator or centurion whose image appears on the company's traveler's cheques, charge cards and credit cards.",
        'Founded': 1850,
        'Industry': ['Banking', 'Financial Services', 'Insurance'],
        'Headquarters': 'New York',
        'Revenue': 33.47,
        'NetIncome': 2.74,
        "Ranking": 24,
        "Percent": 8,
        "Growth": 19139,
        'URL': 'www.AmericanExpress.com'
    },
    {
        "Id": 25,
        'Name': 'Zara SA',
        'Logo': "https://upload.wikimedia.org/wikipedia/commons/f/fd/Zara_Logo.svg",
        'Description': "Zara SA is a Spanish fast fashion (clothing and accessories) retailer based in Arteixo (A Coruña) in Galicia. The company was founded in 1975 by Amancio Ortega and Rosalía Mera. It is the main brand of the Inditex group,[4] the world's largest apparel retailer. The fashion group also owns brands such as Massimo Dutti, Pull&Bear, Bershka, Stradivarius, Oysho, Zara Home, and Uterqüe. Zara as of 2017 manages up to 20 clothing collections a year.",
        'Founded': 1975,
        'Industry': ['Retail', 'Clothing'],
        'Headquarters': 'Spain',
        'Revenue': 18.9,
        'NetIncome': -1,
        "Ranking": 25,
        "Percent": -5,
        "Growth": 17712,
        'URL': 'www.zara.com'
    },
    {
        "Id": 26,
        'Name': 'J.P. Morgan Chase & Co. (JPMorgan Chase)',
        'Logo': "https://upload.wikimedia.org/wikipedia/commons/0/07/J_P_Morgan_Chase_Logo_2008_1.svg",
        'Description': "J.P. Morgan Chase & Co. is an American multinational investment bank and financial services company headquartered in New York City. JPMorgan Chase is the largest bank in the United States, and is ranked by S&P Global as the sixth largest bank in the world by total assets as of 2018, to the amount of $2.534 trillion. It is the world's most valuable bank by market capitalization. As a 'Bulge Bracket' bank, it is a major provider of various investment banking and financial services. It is one of America's Big Four banks, along with Bank of America, Citigroup, and Wells Fargo. JPMorgan Chase is considered to be a universal bank and a custodian bank. The J.P. Morgan brand, historically known as Morgan, is used by the investment banking, asset management, private banking, private wealth management, and treasury & securities services divisions. As of 2017, the bank is one of the largest asset management companies in the world with US$2.789 trillion in assets under management and US$30 trillion in assets under custody. At US$47.7 billion in assets under management, the hedge fund unit of JPMorgan Chase is the fourth largest hedge fund in the United States.",
        'Founded': 2000,
        'Industry': ['Banking', 'Finance', 'Asset Management'],
        'Headquarters': 'New York',
        'Revenue': 109.029,
        'NetIncome': 32.474,
        "Ranking": 26,
        "Percent": 12,
        "Growth": 17567,
        'URL': 'www.jpmorganchase.com'
    },
    {
        "Id": 27,
        'Name': 'IKEA',
        'Logo': "https://upload.wikimedia.org/wikipedia/commons/c/c5/Ikea_logo.svg",
        'Description': "IKEA is a Swedish-founded multinational group that designs and sells ready-to-assemble furniture, kitchen appliances and home accessories, among other useful goods and occasionally home services. It has been the world's largest furniture retailer since at least 2008. It was founded in Sweden in 1943 by 17-year-old carpenter, Ingvar Kamprad, who was listed by Forbes in 2015 as one of the ten richest people in the world, worth more than $40 billion. The company's name is an acronym that consists of the initials of Ingvar Kamprad (name of founder), Elmtaryd (the farm where he grew up), and Agunnaryd (his hometown in Småland, southern Sweden). As of November 2018, there are 424 IKEA stores operating in 52 countries. The company is responsible for approximately 1% of world commercial-product wood consumption, making it one of the largest users of wood in the retail sector.",
        'Founded': 1943,
        'Industry': ['Homeware', 'Furniture', 'Interior Design'],
        'Headquarters': 'Netherlands',
        'Revenue': 40.906,
        'NetIncome': 4.898,
        "Ranking": 27,
        "Percent": -5,
        "Growth": 17458,
        'URL': 'www.ikea.com'
    },
    {
        "Id": 28,
        'Name': 'Gillette',
        'Logo': "https://upload.wikimedia.org/wikipedia/commons/f/fa/Gillette.svg",
        'Description': "Gillette is a brand of safety razors and other personal care products including shaving supplies, owned by the multi-national corporation Procter & Gamble (P&G). Based in Boston, Massachusetts, United States, it was owned by The Gillette Company, a supplier of products under various brands until that company merged into P&G in 2005. The Gillette Company was founded by King C. Gillette in 1901 as a safety razor manufacturer.",
        'Founded': 1901,
        'Industry': ['Razors', 'Peronal Care'],
        'Headquarters': 'Massachusetts',
        'Revenue': -1,
        'NetIncome': -1,
        "Ranking": 28,
        "Percent": -7,
        "Growth": 16864,
        'URL': 'www.gillette.com'
    },
    {
        "Id": 29,
        'Name': 'United Parcel Service, Inc. (UPS)',
        'Logo': "https://upload.wikimedia.org/wikipedia/commons/1/1b/UPS_Logo_Shield_2017.svg",
        'Description': "United Parcel Service (UPS) is an American multinational package delivery and supply chain management company. Along with the central package delivery operation, the UPS brand name (in a fashion similar to that of competitor FedEx) is used to denote many of its divisions and subsidiaries, including its cargo airline (UPS Airlines), freight-based trucking operation (UPS Freight, formerly Overnite Transportation), and retail-based packing and shipping centers (The UPS Store). The global logistics company is headquartered in the U.S. city of Sandy Springs, Georgia, which is a part of the Greater Atlanta metropolitan area.",
        'Founded': 1907,
        'Industry': ['Courier services', 'Supply Chain Management', 'Package Delivery'],
        'Headquarters': 'Georgia',
        'Revenue': 65.872,
        'NetIncome': 4.910,
        "Ranking": 29,
        "Percent": 3,
        "Growth": 16849,
        'URL': 'www.ups.com'
    },
    {
        "Id": 30,
        'Name': 'Hennes & Mauritz AB (H&M)',
        'Logo': "https://upload.wikimedia.org/wikipedia/commons/5/53/H%26M-Logo.svg",
        'Description': "H&M is a Swedish multinational clothing-retail company known for its fast-fashion clothing for men, women, teenagers and children. H&M and its associated companies operate in 62 countries with over 4,500 stores and as of 2015 employed around 132,000 people. It is the second-largest global clothing retailer, just behind Spain-based Inditex (parent company of Zara). The company has a significant online presence, with online shopping available in 33 countries.",
        'Founded': 1947,
        'Industry': ['Clothing', 'Accessories'],
        'Headquarters': 'Sweden',
        'Revenue': 25.191,
        'NetIncome': 2.106,
        "Ranking": 30,
        "Percent": -18,
        "Growth": 16826,
        'URL': 'www.hm.com',
    }
]
